### PR TITLE
Patch for Dragons Descent.

### PR DESCRIPTION
**Pull request by PetMudstone**
Title. Adds patch for the following.
- [Dragon's Descent](https://steamcommunity.com/workshop/filedetails/?id=2026992161)

Edit: Also adds wing prosthetics for all three relevant tech tiers (wooden, prosthetic, bionic). For now they are included in the Dragon's Descent patch and thus will only appear when used with it.

### CODE REVIEW

**Comment by SamuelBucher** [comment]
Does this account for the wings and stuff? Assuming those dragons physically have wings, of course.

**Comment by PetMudstone** [comment]
Actually, I had forgotten to account for the wings. From testing and looking at defs dragons here have wings that affect movement speed. Should I look into implementing wing prostheses then, considering that wings as a discrete body part don't seem to appear often throughout modding?

**Comment by SamuelBucher** [comment]
You should consider doing that, yes. It's not difficult, just use my implementation of animal legs as an example.

**Comment by SamuelBucher** [comment]
Do wings have child parts, like hands have fingers?

**Comment by PetMudstone** [comment]
Nope, I went over the defs beforehand to make sure, there's no child parts whatsoever.

**Comment by SamuelBucher** [comment]
Good. I'm asking because this is important for Medical System Expansion 2 compatibility.

**Pull request merged**
